#!/usr/bin/env python3
"""
PLL Circuit Builder

Assembles design.cir from individual section files in the sections/ directory.
Each .sec file contains one functional block of the PLL.

Usage:
    python build_circuit.py                  # builds design.cir from default sections
    python build_circuit.py --output out.cir # custom output filename
    python build_circuit.py --list           # list available sections
    python build_circuit.py --validate       # check all sections exist and are non-empty

Section order matters: params must come first, sim_control must come last (.end).
"""

import argparse
import os
import sys
from pathlib import Path

# Directory containing section files
SECTIONS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sections")

# Ordered list of sections that compose the full PLL netlist
SECTION_ORDER = [
    "params",
    "pfd",
    "charge_pump",
    "loop_filter",
    "vco",
    "divider",
    "sigma_delta",
    "sim_control",
]

# Header prepended to the assembled file
HEADER = """\
* ============================================================================
* Fractional-N Sigma-Delta PLL Frequency Synthesizer
* ============================================================================
* AUTO-GENERATED by build_circuit.py -- do not edit directly.
* Edit the individual section files in sections/ and re-run the builder.
*
* Target: 2.4 GHz output from 10 MHz reference (N=240)
* Architecture: PFD -> Charge Pump -> 3rd-order Loop Filter -> VCO -> Divider
* ============================================================================
"""


def list_sections():
    """List all available section files."""
    print("Available sections in order:")
    for i, name in enumerate(SECTION_ORDER, 1):
        path = os.path.join(SECTIONS_DIR, f"{name}.sec")
        exists = os.path.isfile(path)
        size = os.path.getsize(path) if exists else 0
        status = f"OK ({size} bytes)" if exists else "MISSING"
        print(f"  {i}. {name:20s} [{status}]")


def validate_sections():
    """Check that all required section files exist and are non-empty."""
    all_ok = True
    for name in SECTION_ORDER:
        path = os.path.join(SECTIONS_DIR, f"{name}.sec")
        if not os.path.isfile(path):
            print(f"  ERROR: {name}.sec is missing")
            all_ok = False
        elif os.path.getsize(path) == 0:
            print(f"  WARNING: {name}.sec is empty")
        else:
            print(f"  OK: {name}.sec")
    return all_ok


def build(output_file="design.cir", verbose=True):
    """Assemble the full netlist from section files."""
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), output_file)
    lines = [HEADER]

    for name in SECTION_ORDER:
        path = os.path.join(SECTIONS_DIR, f"{name}.sec")
        if not os.path.isfile(path):
            print(f"WARNING: Section '{name}' not found at {path}, skipping.")
            continue

        with open(path, "r") as f:
            content = f.read()

        # Add section markers for traceability
        lines.append(f"*==== BEGIN SECTION: {name.upper()} ====")
        lines.append(content.rstrip())
        lines.append(f"*==== END SECTION: {name.upper()} ====")
        lines.append("")

        if verbose:
            line_count = len(content.strip().split("\n"))
            print(f"  Added section: {name:20s} ({line_count} lines)")

    assembled = "\n".join(lines)

    with open(output_path, "w", newline="\n") as f:
        f.write(assembled)

    if verbose:
        total_lines = len(assembled.split("\n"))
        print(f"\nAssembled {len(SECTION_ORDER)} sections -> {output_file} ({total_lines} lines)")

    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Assemble PLL design.cir from section files."
    )
    parser.add_argument(
        "--output", "-o",
        default="design.cir",
        help="Output filename (default: design.cir)",
    )
    parser.add_argument(
        "--list", "-l",
        action="store_true",
        help="List available sections and exit",
    )
    parser.add_argument(
        "--validate", "-v",
        action="store_true",
        help="Validate all sections exist and exit",
    )
    args = parser.parse_args()

    if args.list:
        list_sections()
        return

    if args.validate:
        ok = validate_sections()
        sys.exit(0 if ok else 1)

    print("Building PLL netlist from sections...")
    path = build(args.output)
    print(f"Done. Output: {path}")


if __name__ == "__main__":
    main()
